spring:
  application:
    name: Center
  datasource:
    url: jdbc:mysql://localhost:3306/center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false  #关闭驼峰转换
  global-config:
    db-config:
      logic-delete-field: isDelete  #全局表示逻辑删除的字段
      logic-delete-value: 1  #表示逻辑删除的值
      logic-not-delete-value: 0 #未逻辑删除的值
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example,center.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN